version: '3.3'

services:
  node:
    build:
      context: .
    environment:
      - NODE_ENV=production
    ports:
      - '8341:3000'
    command: yarn run build:prod

networks:
  default:
    external:
      name: chichi-network
