version: "3.3"

services:
  node:
    container_name: cc-auth
    build:
      context: .
    ports:
      - "8341:8341"
    command: yarn run docker:build:prod

networks:
  default:
    external:
      name: chichi-network
