version: "3"
services:
  redis:
    container_name: redis-server
    image: "redis:5"
    ports:
      - "6379:6379"
    # volumes:
    # - "./data/redis:/data"

networks:
  default:
    external:
      name: chichi-network
