version: "3"
services:
  node:
    container_name: json-server
    build:
      context: .
    ports:
      - "8342:8342"
    volumes:
      - "./data:/app/data"
    command: json-server --watch --host 0.0.0.0 /app/data/db.json --port 8342

networks:
  default:
    external:
      name: chichi-network
